dlcache https://updates.jenkins-ci.org/latest/git.hpi
dlcache https://updates.jenkins-ci.org/latest/git-client.hpi
dlcache https://updates.jenkins-ci.org/latest/docker-plugin.hpi
dlcache https://updates.jenkins-ci.org/latest/durable-task.hpi
dlcache https://updates.jenkins-ci.org/latest/scm-api.hpi
dlcache https://updates.jenkins-ci.org/latest/sonar.hpi
dlcache http://updates.jenkins-ci.org/latest/build-monitor-plugin.hpi
dlcache http://updates.jenkins-ci.org/latest/build-with-parameters.hpi
dlcache http://updates.jenkins-ci.org/latest/greenballs.hpi